name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    
    - name: Install dependencies
      run: sudo apt-get install cmake git gcc libsndfile-dev libpng-dev

    - name: Configure cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build and package
      run: cmake --build build -j$(nproc) && cmake --build build --target package

    - name: Upload TGZ archive
      uses: actions/upload-artifact@v3
      with:
          name: TGZ archive (x86_64-gcc)
          path: build/aptdec_*.tar.gz

    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
          name: Debian package (x86_64-gcc)
          path: build/aptdec_*.deb

  build_windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    
    - name: Install dependencies
      run: sudo apt install cmake git mingw-w64 unzip

    - name: Run build script
      run: ./build_windows.sh $BUILD_TYPE

    - name: Upload ZIP archive
      uses: actions/upload-artifact@v3
      with:
          name: ZIP archive (x86_64-MinGW)
          path: winbuild/aptdec_*.zip
  
  build_windows_msvc:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Run build script
      shell: cmd
      run: '"C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat" & build_windows.bat'

    - name: Upload ZIP archive
      uses: actions/upload-artifact@v3
      with:
          name: ZIP archive (x86_64-MSVC)
          path: winbuild/aptdec_*.zip
  
  build_linux_armhf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Run build script
      run: docker run -v $(pwd):/aptdec:z -w /aptdec debian:11 ./build_arm.sh

    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
          name: Debian package (armhf-gcc)
          path: build/aptdec_*.deb

    - name: Upload TGZ archive
      uses: actions/upload-artifact@v3
      with:
          name: TGZ archive (armhf-gcc)
          path: build/aptdec_*.tar.gz
